### ISSUE TITLE
hyper link 

### ISSUE THREAD

**Issue by zarvan9** [peter-kimanzi/app-menu-with-lock-screen#1]
hi How can i add hyper link to cards?
for example on Burgers

**Comment by peter-kimanzi** [comment]
> hi How can i add hyper link to cards? for example on Burgers

Hello @zarvan9  use (a) tag, if you are unable text me again ill do it for you.

**Comment by zarvan9** [comment]
thank you very much for your answer dear @peter-kimanzi .
i tried but unfortunately I did not succeed.
if it was only html, I could link the div. But this page is designed with javascript and I have very little knowledge in javascript.
if its possible for you, add the tag for the "Burgers" div.
Thank you very much for your help.❤️
